#!/bin/bash

new=$1
old=$2
for file in \
   /etc/ssh/ssh_host_rsa_key.pub \
   /etc/ssh/ssh_host_dsa_key.pub \
   /etc/ssh/ssh_host_ed25519_key.pub \
   /etc/ssh/ssh_host_ecdsa_key.pub
do
   [ -f $file ] && sed -i.old -e "s:$old:$new:g" $file
done
