#!/bin/bash

set -e

# Microsoft PGP key
sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor > microsoft.gpg && \
  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

# Adding vscode source and updating packages cache
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' && \
sudo apt-get update

#prerequisites
sudo apt install libgtk2.0-0 libxss1 libgconf-2-4 libasound2 -y

# installing vscode
sudo apt install code -y
