#!/bin/bash

set -e

sudo apt install nvidia-settings xinit xterm libxv1 --no-install-recommends -y

DISPLAY=:0 sudo nvidia-xconfig --enable-all-gpus --use-display-device=none --cool-bits=4

sudo cp -rf nvidia-settings/* /