#!/bin/bash
set -e

# Preparing apt by the node js provided script
sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

# installing nodejs
sudo -H apt install -y nodejs

# upgrading npm
sudo -H npm install npm --upgrade -g

# installing most required packages
sudo -H npm install typescript gulp -g
