#!/bin/bash

set -e

# Installing base tools

# useful for a system stability testing
sudo apt install memtest86+ -y

# system diagnostincs
sudo apt install htop iftop -y 

# network utils
sudo apt install traceroute -y

# most popular remote filesystem access
sudo apt install cifs-utils sshfs -y

# smbclient is added for debugging samba mounting problems
sudo apt install smbclient -y 

# base debugging tool
sudo apt install mc -y

# compression tools
sudo apt install pigz -y