#!/bin/bash

set -e
SCRIPT_ROOT=`dirname "$0"`

# Standard installation from ppa
sudo add-apt-repository ppa:mercurial-ppa/releases -y
sudo apt update
sudo apt install mercurial -y

# installing additional plugins for mercurial
sudo apt install libffi-dev libssl-dev -y
sudo -H pip2 install mercurial-keyring
sudo -H pip2 install keyrings.alt

# Hacking up keryings.alt to silently apply empty master password
sudo patch /usr/local/lib/python2.7/dist-packages/keyrings/alt/file.py $SCRIPT_ROOT/mercurial/file.py.patch

# Clear of compile cache is required due to some bug
sudo rm -f /usr/local/lib/python2.7/dist-packages/keyrings/alt/file.pyc

sudo -H pip2 install git+https://bitbucket.org/dmitriyse/hg-git-git.git

sudo cp -rf $SCRIPT_ROOT/mercurial/dist/* /