#!/bin/bash

sudo add-apt-repository ppa:webupd8team/java -y
sudo apt update
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
sudo apt install oracle-java8-installer -y