#!/bin/bash

set -e

# Import the public repository GPG keys
sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# Register the Microsoft Ubuntu repository and updating apt cache
sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list && \
  sudo apt update

# Install PowerShell
sudo apt install -y powershell