#!/bin/bash 

# Fix mdadm warnings
parts/fix-mdadm-warning

# Installing base tools
../ubuntu/parts/install-base-systools

# Installing remote x11 support
../ubuntu/parts/install-x11-ssh-support

# Installing python2, python3 pip 
../ubuntu/parts/install-sys-pip

# Installing ultimate editor
../ubuntu/parts/install-vscode