#!/bin/bash 

set -e

# Fix mdadm warnings
parts/fix-mdadm-warning

# Installing system miscellaneous scripts
pushd ../ubuntu/parts
./install-sys-misc;popd

# Installing base tools
../ubuntu/parts/install-base-systools

# Installing remote x11 support
../ubuntu/parts/install-x11-ssh-support

# Installing gui tools
../ubuntu/part/install-base-gui-tools

# Installing python2, python3 pip 
../ubuntu/parts/install-sys-pip

# Installing ultimate editor
../ubuntu/parts/install-vscode

# Installing ultimate crossplatform shell
parts/install-powershell

# Installing nodejs LTS
../ubuntu/parts/install-nodejs

# Installing dotnet core
parts/install-dotnet

# Installing mercurial
../ubuntu/parts/install-hg

# Installing tortoisehg
../ubuntu/parts/install-tortoisehg

# Installing docker engine
../ubuntu/parts/install-docker
