#!/bin/bash

set -e

sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y

./install-general-purpose-profile

sudo ../ubuntu/parts/install-kerberos-user.ps1

../ubuntu/parts/install-ldapsearch

sudo ../ubuntu/parts/install-samba-member.ps1
