#!/bin/bash

set -e

# Standard installation from ppa
sudo add-apt-repository ppa:mercurial-ppa/releases -y
sudo apt update
sudo apt install mercurial -y

# installing additional plugins for mercurial
sudo apt install libffi-dev libssl-dev -y
sudo -H pip2 install mercurial-keyring
sudo -H pip2 install keyrings.alt

# Hacking up keryings.alt to silently apply empty master password
sudo patch /usr/local/lib/python2.7/dist-packages/keyrings/alt/file.py file.py.patch

sudo -H pip2 install git+https://bitbucket.org/dmitriyse/hg-git-git.git
