#!/bin/bash
set -e

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt update
sudo apt install docker-ce -y

# Installing docker-clean utility
#curl -s https://raw.githubusercontent.com/ZZROTDesign/docker-clean/v2.0.4/docker-clean |
#sudo tee /usr/local/bin/docker-clean > /dev/null && \
#sudo chmod +x /usr/local/bin/docker-clean